# This workflow will build a MuleSoft project and deploy to CloudHub
name: Setup JDK Maven and Git
description: setting up the required tools

inputs:
  username:
    required: true
    type: string
secrets:
  muleMavenEEUser:
    required: true
  muleMavenEEPwd:
    required: true
  ghUser:
    required: true
  ghPwd:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # add the required maven-repos and settings
    - name: maven-settings-xml
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: |
          [
            {
              "id": "MuleRepository", 
              "name": "MuleRepository", 
              "url": "https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/", 
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "true"
              }
            },
            {
              "id": "github", 
              "name": "CKWParentPOM", 
              "url": "https://maven.pkg.github.com/CKWAG/ckw-mule-parent-pom",
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "true"
              }
            }]
        servers: |
          [
            { 
              "id": "MuleRepository", 
              "username": "${{ secrets.muleMavenEEUser }}", 
              "password": "${{ secrets.muleMavenEEPwd }}" 
            },
            { 
              "id": "github", 
              "username": "${{ secrets.ghUser }}", 
              "password": "${{ secrets.ghPwd }}" 
            }
          ]